#!/bin/bash

# NAME OF CURRENT PROCESS 
appName="CQLSH_UTILS"

# DEFAULT LOG DESTINATIONS 
# 1 for syslog
# 2 for log file
# 3 for telegram
# 4 for verbose
#
destinationsLogs=(1 2 4)

# TELEGRAM CLIENTS
telegramClient="/usr/local/bin/sendtelegram"
telegramClientConfigurationFile="/etc/telegramrc"

#CONFIGURATION DIR
MCS_FOLDER="$(pwd)/MCS_FOLDER"
RAW_FOLDER="$MCS_FOLDER/raw"
SOURCE_FOLDER="$RAW_FOLDER/source"
SHUF_FOLDER="$RAW_FOLDER/shuf"
CQLSH_CONFIGURATION="$MCS_FOLDER/cqlsh.d"

#CONNECTION CONFIGURATION
SOURCE_SERVER="172.19.0.1"
SOURCE_KEYSPACE="voltron"
TARGET_SERVER="cassandra.eu-west-1.amazonaws.com"
TARGET_KEYSPACE="datahub"